#!/bin/sh

print_usage() {
	echo "Usage: ${0##*/} start|stop|restart"
}

case $1 in
	start)
		echo "Starting Prophet..."
		export RAILS_ENV=production
		export SECRET_KEY_BASE=$(rake secret)
		export RAILS_SERVE_STATIC_FILES=true
		rake assets:precompile
		rake db:migrate
		rails s --binding 0.0.0.0 -d
		echo "Prophet started.";;
	stop)
		kill -9 $(cat tmp/pids/server.pid 2> /dev/null) 2> /dev/null
		echo "Prophet stopped.";;
	restart)
		$0 stop
		$0 start;;
	*)
		print_usage
		exit 1;;
esac

exit 0
